import React from 'react'

const About = () => {
  return (
    <div className='max-w-6xl mx-auto space-y-4 p-4'>
      <h1 className='text-2xl font-medium text-amber-600'>About</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit tempora necessitatibus consectetur! Eaque libero soluta animi tenetur odio maiores, maxime impedit deleniti harum nemo itaque molestiae officia ad aspernatur dicta aliquam quam ipsum illo esse voluptatum architecto vel? Adipisci minus, amet atque, et voluptates reiciendis vel delectus exercitationem corrupti molestias dolorum. Ipsa facilis quis laborum, earum inventore repellat exercitationem voluptas hic omnis nemo quasi quas maxime itaque autem ab eum soluta, reiciendis cum ducimus similique odio odit qui officiis. Debitis exercitationem repudiandae quasi ea. Odio blanditiis modi nisi veniam quia, architecto natus, ipsam optio placeat dolorum facere adipisci nobis minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit tempora necessitatibus consectetur! Eaque libero soluta animi tenetur odio maiores, maxime impedit deleniti harum nemo itaque molestiae officia ad aspernatur dicta aliquam quam ipsum illo esse voluptatum architecto vel? Adipisci minus, amet atque, et voluptates reiciendis vel delectus exercitationem corrupti molestias dolorum. Ipsa facilis quis laborum, earum inventore repellat exercitationem voluptas hic omnis nemo quasi quas maxime itaque autem ab eum soluta, reiciendis cum ducimus similique odio odit qui officiis. Debitis exercitationem repudiandae quasi ea. Odio blanditiis modi nisi veniam quia, architecto natus, ipsam optio placeat dolorum facere adipisci nobis minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit tempora necessitatibus consectetur! Eaque libero soluta animi tenetur odio maiores, maxime impedit deleniti harum nemo itaque molestiae officia ad aspernatur dicta aliquam quam ipsum illo esse voluptatum architecto vel? Adipisci minus, amet atque, et voluptates reiciendis vel delectus exercitationem corrupti molestias dolorum. Ipsa facilis quis laborum, earum inventore repellat exercitationem voluptas hic omnis nemo quasi quas maxime itaque autem ab eum soluta, reiciendis cum ducimus similique odio odit qui officiis. Debitis exercitationem repudiandae quasi ea. Odio blanditiis modi nisi veniam quia, architecto natus, ipsam optio placeat dolorum facere adipisci nobis minima?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit tempora necessitatibus consectetur! Eaque libero soluta animi tenetur odio maiores, maxime impedit deleniti harum nemo itaque molestiae officia ad aspernatur dicta aliquam quam ipsum illo esse voluptatum architecto vel? Adipisci minus, amet atque, et voluptates reiciendis vel delectus exercitationem corrupti molestias dolorum. Ipsa facilis quis laborum, earum inventore repellat exercitationem voluptas hic omnis nemo quasi quas maxime itaque autem ab eum soluta, reiciendis cum ducimus similique odio odit qui officiis. Debitis exercitationem repudiandae quasi ea. Odio blanditiis modi nisi veniam quia, architecto natus, ipsam optio placeat dolorum facere adipisci nobis minima?</p>
    </div>
  )
}

export default About